sudo: required
dist: trusty
services:
  - docker
language: java
jdk:
  - oraclejdk8
install:
  - docker build --tag garethahealy/elastoplast-base:latest base/src/main/docker/
  - docker build --tag garethahealy/elastoplast-rule1:latest rule1/src/main/docker/
script:
  - mvn clean install -Dgpg.skip=true
cache:
  directories:
  - $HOME/.m2
  - $HOME/.victims
